// Fetches every London plaque from Open Plaques into src/data/plaques.json.
//
// THE DATA AND ITS LICENCE
// Open Plaques' own About page: "The data generated by the project are free
// to use under a Public Domain declaration." That is why this can live in the
// repo at all. Attribution is still given on the page, because it is right.
//
// WHY THIS SCRIPT IS SHAPED LIKE THIS
// The site's bulk endpoints are broken or fragile: /data errors, the one-shot
// area dump (their own datadump.sh uses it against localhost) 503s in
// production, and a burst of requests gets an IP rate-limited - which
// happened while researching this. What reliably works is the paginated CSV,
// 20 rows a page. So:
//
//   - one request every FOUR SECONDS, politely below any sane limit
//   - every page cached to data/plaques-cache/, so a rerun never refetches
//   - 503s back off exponentially up to five minutes and resume
//   - the whole run is resumable: kill it, run it again, it continues
//
// London is ~3,500 plaques = ~175 pages = ~12 minutes when the site is
// healthy. Run it, go and do something else.
//
//   node scripts/fetch-plaques.mjs           # fetch missing pages + build JSON
//   node scripts/fetch-plaques.mjs --build   # rebuild JSON from cache only
//
import fs from "node:fs";
import path from "node:path";

const CACHE = "data/plaques-cache";
// public/ so the page can fetch() it client-side - 3,500 inscriptions inlined
// into the HTML would triple the page weight for no benefit.
const OUT = "public/plaques.json";
const BASE = "https://openplaques.org/places/gb/areas/london/plaques.csv";
const UA =
  "london-travel-geek/1.0 (building a public plaques map; polite 4s interval; contact via github.com/RRM1000/london-travel-geek)";
const DELAY_MS = 4000;
const buildOnly = process.argv.includes("--build");

fs.mkdirSync(CACHE, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---------------------------------------------------------------- CSV parser
// Handles quoted fields with embedded commas, quotes and newlines - plaque
// inscriptions contain all three.
function parseCsv(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQ = false;
      } else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.length > 1 || row[0] !== "") rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows;
}

async function fetchPage(page) {
  const file = path.join(CACHE, `page-${String(page).padStart(3, "0")}.csv`);
  if (fs.existsSync(file)) return fs.readFileSync(file, "utf8");

  let backoff = 30_000;
  for (let attempt = 1; attempt <= 8; attempt++) {
    const res = await fetch(`${BASE}?page=${page}`, {
      headers: { "user-agent": UA, accept: "text/csv" },
    }).catch(() => null);

    if (res?.ok) {
      const text = await res.text();
      if (text.includes("<!DOCTYPE") || text.includes("Application Error")) {
        // 200 wrapping their error page - treat as a failure
      } else {
        fs.writeFileSync(file, text);
        return text;
      }
    }
    const status = res ? res.status : "network";
    console.log(`  page ${page}: ${status}, backing off ${backoff / 1000}s (attempt ${attempt}/8)`);
    await sleep(backoff);
    backoff = Math.min(backoff * 2, 300_000);
  }
  return null;
}

// ------------------------------------------------------------------ fetching
if (!buildOnly) {
  console.log("fetching London plaques, 20 per page, 4s apart...");
  let page = 1, empties = 0;
  for (; page < 400; page++) {
    const text = await fetchPage(page);
    if (text === null) {
      console.log(`stopping at page ${page}: the site would not serve it after 8 attempts.`);
      console.log("the run is resumable - run this script again later and it continues here.");
      break;
    }
    const rows = parseCsv(text);
    if (rows.length <= 1) {
      empties++;
      if (empties >= 2) { console.log(`end of data at page ${page}.`); break; }
    } else {
      empties = 0;
      if (page % 10 === 0) console.log(`  page ${page} cached (${rows.length - 1} rows)`);
    }
    await sleep(DELAY_MS);
  }
}

// ------------------------------------------------------------------ building
// TWO SOURCES, SEED THEN CACHE. Open Plaques' live CSV endpoint was down hard
// when this map was built - eight attempts over 35 minutes, every one a 503 -
// but their official GB dump of 2021-05-14 survives, mirrored bit-identically
// in two independent GitHub repos. Public domain data, so the mirror is as
// legitimate as the original. data/plaques-seed.csv is that dump; the live
// cache pages overlay it by id whenever the fetcher manages to run, so the
// dataset starts complete-but-2021 and freshens toward current.
const files = fs.readdirSync(CACHE).filter((f) => f.endsWith(".csv")).sort();
const SEED = "data/plaques-seed.csv";
if (!files.length && !fs.existsSync(SEED)) {
  console.log("no cached pages and no seed dump - nothing to build.");
  process.exit(0);
}

let header = null;
const seen = new Map();

if (fs.existsSync(SEED)) {
  const rows = parseCsv(fs.readFileSync(SEED, "utf8"));
  const seedHeader = rows[0].map((h) => h.replace(/^﻿/, "").trim());
  for (const r of rows.slice(1)) {
    const o = Object.fromEntries(seedHeader.map((h, i) => [h, r[i] ?? ""]));
    if (o.id) seen.set(o.id, o);
  }
  console.log(`seed dump: ${seen.size} GB plaques from 2021-05-14`);
}
for (const f of files) {
  const rows = parseCsv(fs.readFileSync(path.join(CACHE, f), "utf8"));
  if (!rows.length) continue;
  if (!header) header = rows[0].map((h) => h.replace(/^﻿/, "").trim());
  for (const r of rows.slice(1)) {
    const o = Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""]));
    if (o.id) seen.set(o.id, o);
  }
}

// --------------------------------------------------------------- category
// The dataset carries a real occupation field, lead_subject_roles - a JSON
// array like ["novelist","journalist","policeman"] - but it is not a clean
// taxonomy: honours (knight bachelor, OBE), relationships (son of john
// dickens), and building types (public house, gate) sit in the same list as
// genuine occupations (actor, composer, architect). "Colour" is a common
// point of confusion here too - it is the plaque's physical material, not a
// subject: a "film cell" plaque is shaped like a strip of film, usually for
// someone in the FILM category, but the two are unrelated axes.
//
// This maps the roles that actually occur often enough to matter into eight
// occupation categories, first match wins; anything left over - honours-only
// tags, family relationships, building/street/inn types, and genuinely rare
// occupations - falls to "other" rather than being force-fit. Checked against
// the London slice of the 2021 dump: ~46% of London plaques land in "other",
// which is expected, not a shortfall - it is dominated by non-person plaques
// (buildings, streets, inns) and honours-only entries, not missed occupations.
const CATEGORY_RULES = [
  ["music", [
    "composer", "musician", "singer", "songwriter", "conductor", "organist",
    "violinist", "pianist", "opera singer", "rock legend", "band member",
    "master of the king's music", "master of the queen's music",
  ]],
  ["film-tv-theatre", [
    "actor", "actress", "film star", "film director", "film maker", "director",
    "producer", "comedian", "comic actor", "comedy actor", "entertainer",
    "playwright", "dramatist", "theatre", "broadcaster", "film pioneer",
  ]],
  ["literature", [
    "poet", "novelist", "writer", "author", "essayist", "diarist", "critic",
    "playwright", "dramatist", "publisher", "journalist", "poet laureate",
    "nobel literature laureate", "children's writer", "librettist",
    "historian", "man of letters", "philosopher",
  ]],
  ["art-design", [
    "artist", "painter", "sculptor", "illustrator", "designer", "architect",
    "portrait painter", "landscape painter", "royal academician", "engraver",
    "photographer", "printmaker", "cartoonist",
  ]],
  ["science-medicine", [
    "scientist", "physicist", "chemist", "mathematician", "engineer",
    "civil engineer", "inventor", "physician", "surgeon", "doctor",
    "astronomer", "botanist", "naturalist", "geologist", "fellow of the royal society",
    "nobel physics laureate", "nobel physiology or medicine laureate",
    "nobel chemistry laureate", "psychologist", "biologist", "man of science",
  ]],
  ["politics-military", [
    "member of parliament", "prime minister", "statesman", "politician",
    "soldier", "admiral", "general", "field-marshal", "captain", "colonel",
    "victoria cross recipient", "military cross recipient", "suffragette",
    "suffragist", "reformer", "abolitionist", "social reformer",
    "chancellor of the exchequer", "diplomat", "cardinal", "reverend", "theologian",
    "philanthropist", "mayor of london", "trade unionist", "campaigner", "activist",
  ]],
  ["sport", [
    "cricketer", "footballer", "athlete", "boxer", "olympian", "sportsman",
    "sportswoman", "rower", "golfer",
  ]],
  ["royalty", [
    "king of england", "king of scots", "king of the united kingdom",
    "queen of the united kingdom", "prince of wales", "prince", "princess",
    "empress of india", "duke", "duchess", "president of the united states",
  ]],
];

// organisations is stored the same JSON-array-shaped way as lead_subject_roles
// (e.g. '["English Heritage", "London County Council"]') - shown raw, every
// popup and list row would print literal brackets and quotes.
function cleanOrg(raw) {
  if (!raw) return "";
  try {
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr.join(", ") : String(arr);
  } catch {
    return raw;
  }
}

function categorise(rolesRaw) {
  if (!rolesRaw) return "";
  let roles;
  try { roles = JSON.parse(rolesRaw); } catch { roles = [rolesRaw]; }
  const lower = roles.map((r) => String(r).toLowerCase());
  for (const [category, keywords] of CATEGORY_RULES) {
    if (lower.some((r) => keywords.some((k) => r.includes(k)))) return category;
  }
  return "other";
}

// Slim to what the map needs. Inscriptions ARE the content, so they stay.
const LONDON = { latMin: 51.2, latMax: 51.75, lngMin: -0.6, lngMax: 0.4 };
const plaques = [];
let noCoords = 0, outside = 0;
for (const o of seen.values()) {
  const lat = parseFloat(o.latitude), lng = parseFloat(o.longitude);
  if (!isFinite(lat) || !isFinite(lng)) { noCoords++; continue; }
  if (lat < LONDON.latMin || lat > LONDON.latMax || lng < LONDON.lngMin || lng > LONDON.lngMax) {
    outside++; continue;
  }
  plaques.push({
    id: Number(o.id),
    title: o.title,
    inscription: o.inscription,
    lat: Math.round(lat * 1e5) / 1e5,
    lng: Math.round(lng * 1e5) / 1e5,
    colour: (o.colour || "").toLowerCase(),
    org: cleanOrg(o.organisations),
    erected: o.erected || "",
    address: o.address || "",
    subject: o.lead_subject_name || "",
    category: categorise(o.lead_subject_roles),
  });
}
plaques.sort((a, b) => a.id - b.id);

const colours = {};
for (const p of plaques) colours[p.colour || "unknown"] = (colours[p.colour || "unknown"] ?? 0) + 1;

const categories = {};
for (const p of plaques) categories[p.category || "none"] = (categories[p.category || "none"] ?? 0) + 1;

fs.writeFileSync(
  OUT,
  JSON.stringify(
    {
      note:
        "Open Plaques data, public domain per openplaques.org/about. " +
        "Fetched by scripts/fetch-plaques.mjs; rerun it to refresh.",
      fetched: files.length
        ? new Date().toISOString().slice(0, 10)
        : "2021-05-14 dump; live refresh pending",
      count: plaques.length,
      plaques,
    },
    null,
    1,
  ) + "\n",
);

console.log(`\n${plaques.length} London plaques -> ${OUT}`);
console.log(`  dropped: ${noCoords} without coordinates, ${outside} outside the London box`);
console.log(`  colours: ${Object.entries(colours).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(", ")}`);
console.log(`  categories: ${Object.entries(categories).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(", ")}`);
const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`  size: ${kb} KB`);
