// The neighbourhood table both sheet tabs are keyed off.
//
// This used to live inside write-restaurants-v2.mjs. It moved here when the
// Experiences tab was added, because two copies of a 130-row lookup is two
// copies that drift - and a zone that disagrees between tabs is invisible
// until someone notices Shoreditch is Zone 1 on one and Zone 2 on the other.
//
// Zone is the TfL fare zone; District is the compass split London actually
// uses. They answer different questions and neither derives from the other:
// Shoreditch is Zone 1 but nobody calls it central, Canary Wharf is Zone 2
// and firmly East.
export const HOODS = {
  "Aldgate":             { zone: "1",   district: "East" },
  "Battersea":           { zone: "1",   district: "South" },
  "Bermondsey":          { zone: "1–2", district: "South" },
  "Belgravia":           { zone: "1",   district: "Central" },
  "Bethnal Green":       { zone: "2",   district: "East" },
  "Bloomsbury":          { zone: "1",   district: "Central" },
  "Borough":             { zone: "1",   district: "South" },
  "Brick Lane":          { zone: "1",   district: "East" },
  "Bow":                 { zone: "2",   district: "East" },
  "Brixton":             { zone: "2",   district: "South" },
  "Barnes":              { zone: "3",   district: "West" },
  "Camberwell":          { zone: "2",   district: "South" },
  "Chingford":           { zone: "5",   district: "North" },
  "Victoria Park":       { zone: "2",   district: "East" },
  "East Finchley":       { zone: "3",   district: "North" },
  "Camden Town":         { zone: "2",   district: "North" },
  "Canary Wharf":        { zone: "2",   district: "East" },
  "Clapton":             { zone: "2",   district: "East" },
  "Chelsea":             { zone: "1–2", district: "West" },
  "Chiswick":            { zone: "2–3", district: "West" },
  "Royal Docks":           { zone: "3",   district: "East" },
  "Golders Green":         { zone: "3",   district: "North" },
  "White City":            { zone: "2",   district: "West" },
  "Angel":                 { zone: "1",   district: "North" },
  "Kentish Town":          { zone: "2",   district: "North" },
  "Bayswater":             { zone: "1",   district: "West" },
  "Edgware Road":          { zone: "1",   district: "Central" },
  "Shepherd's Bush":       { zone: "2",   district: "West" },
  "Tooting":               { zone: "3",   district: "South" },
  "Haggerston":            { zone: "2",   district: "East" },
  "Holborn":               { zone: "1",   district: "Central" },
  "Harlesden":             { zone: "3",   district: "North" },
  "Finsbury Park":         { zone: "2",   district: "North" },
  "Acton":                 { zone: "3",   district: "West" },
  "Leytonstone":           { zone: "3",   district: "East" },
  "New Malden":            { zone: "4",   district: "South" },
  "Deptford":              { zone: "2",   district: "South" },
  "Earl's Court":          { zone: "1",   district: "West" },
  "Wimbledon":             { zone: "3",   district: "South" },
  "Newington Green":       { zone: "2",   district: "North" },
  "Tottenham":             { zone: "3",   district: "North" },
  "Crouch End":            { zone: "3",   district: "North" },
  "Maida Vale":            { zone: "2",   district: "West" },
  "Harringay":             { zone: "3",   district: "North" },
  "Primrose Hill":         { zone: "2",   district: "North" },
  "Queen's Park":          { zone: "2",   district: "North" },
  "Farringdon":            { zone: "1",   district: "Central" },
  "Holland Park":          { zone: "2",   district: "West" },
  "London Bridge":         { zone: "1",   district: "Central" },
  "South Bank":            { zone: "1",   district: "Central" },
  "Selhurst":              { zone: "4",   district: "South" },
  "Sydenham":              { zone: "3",   district: "South" },
  "Balham":                { zone: "3",   district: "South" },
  "Queensway":             { zone: "1",   district: "West" },
  "St John's Wood":        { zone: "2",   district: "North" },
  "Hackney Wick":          { zone: "2",   district: "East" },
  "East Dulwich":          { zone: "2",   district: "South" },
  "Exmouth Market":        { zone: "1",   district: "Central" },
  "Isle of Dogs":          { zone: "2",   district: "East" },
  "Greenwich Peninsula":   { zone: "2",   district: "East" },
  "Stratford":             { zone: "3",   district: "East" },
  "Crystal Palace":        { zone: "3",   district: "South" },
  "Somers Town":           { zone: "1",   district: "North" },
  "Hoxton":                { zone: "1",   district: "East" },
  "Smithfield":            { zone: "1",   district: "Central" },
  "Liverpool Street":      { zone: "1",   district: "Central" },
  "Chinatown":           { zone: "1",   district: "Central" },
  "City of London":      { zone: "1",   district: "Central" },
  "Clapham":             { zone: "2",   district: "South" },
  "Clerkenwell":         { zone: "1",   district: "Central" },
  "Covent Garden":       { zone: "1",   district: "Central" },
  "Dalston":             { zone: "2",   district: "East" },
  "Ealing":              { zone: "3",   district: "West" },
  "Elephant and Castle": { zone: "1–2", district: "South" },
  "Fitzrovia":           { zone: "1",   district: "Central" },
  "Fulham":              { zone: "2",   district: "West" },
  "Greenwich":           { zone: "2–3", district: "South" },
  "Hackney":             { zone: "2",   district: "East" },
  "Hammersmith":         { zone: "2",   district: "West" },
  "Hampstead":           { zone: "2–3", district: "North" },
  "Highgate":            { zone: "3",   district: "North" },
  "Highbury":            { zone: "2",   district: "North" },
  "Holloway":            { zone: "2",   district: "North" },
  "Islington":           { zone: "1–2", district: "North" },
  "Kensington":          { zone: "1–2", district: "West" },
  "Kew":                 { zone: "3",   district: "West" },
  "King's Cross":        { zone: "1",   district: "North" },
  "Knightsbridge":       { zone: "1",   district: "West" },
  "London Fields":       { zone: "2",   district: "East" },
  "Marylebone":          { zone: "1",   district: "Central" },
  "Mayfair":             { zone: "1",   district: "Central" },
  "Paddington":          { zone: "1",   district: "West" },
  "Notting Hill":        { zone: "1–2", district: "West" },
  "Peckham":             { zone: "2",   district: "South" },
  "Piccadilly":          { zone: "1",   district: "Central" },
  "Pimlico":             { zone: "1",   district: "Central" },
  "Richmond":            { zone: "4",   district: "West" },
  "Petersham":           { zone: "4",   district: "West" },
  "Little Venice":       { zone: "2",   district: "West" },
  "Shad Thames":         { zone: "1–2", district: "South" },
  "Shoreditch":          { zone: "1",   district: "East" },
  "Soho":                { zone: "1",   district: "Central" },
  "St James's":          { zone: "1",   district: "Central" },
  "Stoke Newington":     { zone: "2",   district: "North" },
  "Stockwell":           { zone: "2",   district: "South" },
  "Southall":            { zone: "4",   district: "West" },
  "South Kensington":    { zone: "1",   district: "West" },
  "Spitalfields":        { zone: "1",   district: "East" },
  "Trafalgar Square":    { zone: "1",   district: "Central" },
  "Victoria":            { zone: "1",   district: "Central" },
  "Wandsworth":          { zone: "2",   district: "South" },
  "Wapping":             { zone: "2",   district: "East" },
  "Wembley":             { zone: "4",   district: "North" },
  "Walthamstow":         { zone: "3",   district: "East" },
  "Colindale":           { zone: "4",   district: "North" },
  "Croydon":             { zone: "5",   district: "South" },
  "Canada Water":        { zone: "2",   district: "South" },
  "Vauxhall":            { zone: "1–2", district: "South" },
  "West Hampstead":      { zone: "2",   district: "North" },
  "Whitechapel":         { zone: "2",   district: "East" },
  "Westminster":         { zone: "1",   district: "Central" },
  "Wood Wharf":          { zone: "2",   district: "East" },
  // Added by the Indian guide pass. Six rows carried "LOCATION UNCONFIRMED"
  // while the enrichment cache already held their address - the geography was
  // known, it just had no hood to hang on.
  "Brockley":            { zone: "2–3", district: "South" },
  "East Ham":            { zone: "3–4", district: "East" },
  "Homerton":            { zone: "2",   district: "East" },
  "Leicester Square":    { zone: "1",   district: "Central" },
  // Added by the jazz-dining pass.
  "Kennington":          { zone: "2",   district: "South" },
  // Added by the pizza consensus pass, 2026-08-22. Leyton is where the
  // National Pizza of the Year 2025 is actually cooked, which is the whole
  // argument for the sheet not stopping at Zone 2.
  "Leyton":              { zone: "3",   district: "East" },
  // Added by the celebrity-owned pass, 2026-08-23.
  "Limehouse":           { zone: "2",   district: "East" },
  // Added by the unusual-venues pass, 2026-08-23. The floating pagoda at
  // Cumberland Basin sits on the park's northern edge, not in Camden Town.
  "Regent's Park":       { zone: "1",   district: "North" },
  // Added by the fish-and-chips consensus pass, 2026-08-23.
  "Waterloo":            { zone: "1",   district: "Central" },
  "Herne Hill":          { zone: "3",   district: "South" },
  // Added by the vegetarian and vegan pass, 2026-08-23. Drummond Street by
  // Euston is the cheapest concentration of vegetarian Indian food in London
  // and had no entry at all.
  "Euston":              { zone: "1",   district: "Central" },
  "Old Street":          { zone: "1",   district: "Central" },
};

/** True when a row sits in the visitor core. Zone 1 and 1-2 both count. */
export const isCentral = (zone) => /^1/.test(zone ?? "");

export const DISTRICTS = ["Central", "North", "East", "South", "West"];
