// Generates an article SKELETON from the sheet. Emits everything around the
// sentence - headings, facts strips, cross-references, ordering - and leaves
// the prose slot empty.
//
// It deliberately does NOT write the prose. Generated prose drifts between
// builds, cannot be reviewed as a diff, and reads like the twelve-identical-
// paragraphs problem this whole exercise exists to avoid. Facts regenerate,
// sentences are written once by a person.
//
//   node scripts/scaffold.mjs nicest-dining
//   node scripts/scaffold.mjs best-pizza --central
//   node scripts/scaffold.mjs best-value --central --out=scratch/pizza.md
//
// Ordering: `lists` supports an optional rank, "nicest-dining:2". Ranked
// entries come first in rank order; unranked follow, cheapest first, so an
// unordered list still reads as a progression rather than as insertion order.
//
import fs from "node:fs";
import path from "node:path";
import { readTab } from "./sheets.mjs";

const args = process.argv.slice(2);
const listName = args.find((a) => !a.startsWith("--"));
const centralOnly = args.includes("--central");
const outArg = args.find((a) => a.startsWith("--out="));

if (!listName) {
  console.error("usage: node scripts/scaffold.mjs <list-name> [--central] [--out=path]");
  process.exit(1);
}

const rows = (await readTab("Restaurants v2")).filter((r) => r.Status === "open");
const cache = fs.existsSync("data/enrichment.json")
  ? JSON.parse(fs.readFileSync("data/enrichment.json", "utf8"))
  : {};

// "nicest-dining:2" -> { name, rank }
const parseLists = (s) =>
  String(s ?? "").split(",").map((x) => x.trim()).filter(Boolean).map((x) => {
    const [name, rank] = x.split(":");
    return { name: name.trim(), rank: rank ? Number(rank) : null };
  });

const PRICE_ORDER = { "£": 1, "££": 2, "£££": 3, "££££": 4 };

let entries = rows
  .map((r) => ({ r, hit: parseLists(r.Lists).find((l) => l.name === listName) }))
  .filter((x) => x.hit)
  .filter((x) => !centralOnly || x.r["Central London"] === "TRUE")
  .map((x) => ({ ...x, rank: x.hit.rank }));

entries.sort((a, b) => {
  if (a.rank != null && b.rank != null) return a.rank - b.rank;
  if (a.rank != null) return -1;
  if (b.rank != null) return 1;
  return (PRICE_ORDER[a.r["Price Band"]] ?? 9) - (PRICE_ORDER[b.r["Price Band"]] ?? 9);
});

if (!entries.length) {
  console.error(`no open rows in list "${listName}"${centralOnly ? " with Central London = TRUE" : ""}`);
  const all = new Set(rows.flatMap((r) => parseLists(r.Lists).map((l) => l.name)));
  console.error(`available lists: ${[...all].sort().join(", ")}`);
  process.exit(1);
}

// -------------------------------------------------------- cross-references ---
// The connective tissue. A list of venues is a table; a list that tells you
// what is four minutes away is a route.
const haversine = (a, b) => {
  const R = 6371000, t = (d) => (d * Math.PI) / 180;
  const dLat = t(b.lat - a.lat), dLng = t(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 +
    Math.cos(t(a.lat)) * Math.cos(t(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
};
const walkMin = (m) => Math.max(1, Math.round((m * 1.3) / 80));

function nearestOnList(slug) {
  const me = cache[slug];
  if (!me?.lat) return null;
  let best = null;
  for (const e of entries) {
    if (e.r.Slug === slug) continue;
    const other = cache[e.r.Slug];
    if (!other?.lat) continue;
    const d = haversine(me, other);
    if (d < 900 && (!best || d < best.d)) best = { name: e.r.Name, d };
  }
  return best ? { name: best.name, min: walkMin(best.d), metres: Math.round(best.d) } : null;
}

// ---------------------------------------------------------------- render ---
const factStrip = (r) => {
  const bits = [
    r["Price Band"],
    r.Neighbourhood,
    r["Walk Min"] && r["Nearest Station"] ? `${r["Walk Min"]} min from ${r["Nearest Station"]}` : null,
    r["Booking Lead Time"] === "walk-in" ? "walk-in only"
      : r["Booking Lead Time"] ? `book ${r["Booking Lead Time"]} ahead` : null,
    r.Signals,
  ].filter(Boolean);
  return `*${bits.join(" · ")}*`;
};

const out = [];
out.push(`<!-- SCAFFOLD: ${listName}${centralOnly ? " (Central London)" : ""} - ${entries.length} entries`);
out.push(`     Generated by scripts/scaffold.mjs. Facts and distances regenerate;`);
out.push(`     the prose under each heading does not. Write those by hand. -->`);
out.push("");

for (const [i, { r }] of entries.entries()) {
  out.push(`## ${i + 1}. ${r.Name}`);
  out.push("");
  out.push(factStrip(r));
  out.push("");
  out.push(`<!-- angle: ${r.Angle || "UNSET"} -->`);
  if (r["Why Go"]) out.push(`<!-- raw note: ${r["Why Go"]} -->`);
  if (r["Signature Dish"]) out.push(`<!-- signature: ${r["Signature Dish"]} -->`);
  if (r["Operational Summary"]) out.push(`<!-- operational: ${r["Operational Summary"]} -->`);
  out.push("");
  out.push("TODO write 2-3 sentences here.");
  out.push("");
  const near = nearestOnList(r.Slug);
  if (near) out.push(`**${near.min} minutes from ${near.name}.**`, "");
  if (r["Booking URL"]) out.push(`[Book](${r["Booking URL"]})`, "");
}

const md = out.join("\n");
if (outArg) {
  const p = outArg.slice("--out=".length);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, md + "\n");
  console.log(`wrote ${p}`);
} else {
  console.log(md);
}

// ------------------------------------------------------------ flow report ---
// The whole reason `angle` exists: two neighbours taking the same approach is
// the monotony this is meant to prevent, so it is reported as a defect.
console.error(`\n--- FLOW CHECK: ${listName} (${entries.length} entries) ---`);
const clashes = [];
for (let i = 1; i < entries.length; i++) {
  const a = entries[i - 1].r, b = entries[i].r;
  if (a.Angle && a.Angle === b.Angle) clashes.push(`  ${i}. ${a.Name} -> ${b.Name}  both "${a.Angle}"`);
}
if (clashes.length) {
  console.error(`${clashes.length} adjacent angle clash(es) - reorder or re-angle:`);
  clashes.forEach((c) => console.error(c));
} else {
  console.error("no adjacent angle clashes");
}

const angles = {};
for (const { r } of entries) angles[r.Angle || "UNSET"] = (angles[r.Angle || "UNSET"] ?? 0) + 1;
console.error(`angle spread: ${Object.entries(angles).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(", ")}`);

const linked = entries.filter(({ r }) => nearestOnList(r.Slug)).length;
console.error(`cross-references: ${linked}/${entries.length} entries have a walkable neighbour`);
const noRank = entries.filter((e) => e.rank == null).length;
if (noRank) console.error(`unranked: ${noRank}/${entries.length} - add "${listName}:N" in Lists to fix the order`);
